codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...75"

  status:
    project:
      default: false
    patch:
      default: false


parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  require_changes: false
  layout: "reach,diff,flags,tree"
  behavior: default


ignore:
  - "thirdparty/"
  - "tests/"