name: Bug Report
description: Report a bug or unexpected behavior (e.g., crash, incorrect vector query, memory leak)
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting! Please provide detailed info so we can reproduce and fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: |
        e.g. "Query with vector field crashes when using Zvec Python API"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Exact steps to trigger the issue (code snippets welcome)
      placeholder: |
        1. Build Zvec with CMake (Debug/Release)
        2. Run Python script: `python test.py`
        3. Call `collection.query(VectorQuery())`
        4. Process segfaults / hangs / returns wrong results
      render: python
    validations:
      required: true

  - type: textarea
    id: logs_or_trace
    attributes:
      label: Logs / Stack Trace
      description: Paste relevant logs, LLDB/GDB backtrace, or CI failures
      placeholder: |
        Thread 1 "python" received signal SIGSEGV, Segmentation fault.
        0x0000000104a2c3f0 in std::__1::shared_ptr<...>::...
      render: shell
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: macOS 14 (M1), Ubuntu 22.04, Windows 11 (WSL2)
    validations:
      required: true

  - type: input
    id: build_env
    attributes:
      label: Build & Runtime Environment
      description: Compiler, CMake, Python, key dependencies
      placeholder: |
        clang 15.0.0, CMake 4.1.2, Python 3.11.9, magic_enum v0.9.7 (via git submodule)
    validations:
      required: true

  - type: checkboxes
    id: additional_context
    attributes:
      label: Additional Context
      options:
        - label: I've checked `git status` — no uncommitted submodule changes
        - label: I built with `CMAKE_BUILD_TYPE=Debug`
        - label: This occurs with or without `COVERAGE=ON`
        - label: The issue involves Python ↔ C++ integration (pybind11)